openapi: 3.0.0
info:
  title: Sample API 2
  description: A simple API to demonstrate OpenAPI specification.
  version: 1.0.1
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      summary: Get Posts 2
      description: Retrieve a list of posts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
                      example: 1
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "Sample Post test 2"
                    body:
                      type: string
                      example: "This is a sample post."
